print("addition : 5+3 = ",                    5+3)
print("soustraction : 5-3 = ",                5-3)
print("division en python 3 : 5/3 = ",        5/3) 
print("division en python 2 : 5/float(3) = ", 5/float(3)) 
print("division entière : 5//3 = ",           5//3) 
print("multiplication : 5*3 = ",              5*3) 
print("puissance : 5**3 = ",                  5**3)